config/routes.rb
Led::Application.routes.draw do
  root :to => "front#home"
  match 'front(/:action)', :controller => 'front'

  resources :products
  resources :categories
  resources :news
  resources :contacts
  resources :enquiries
  resources :users
  resources :helps

  namespace :admin do
    root :to=>"products#index"

    resources :products
    resources :categories
    resources :news
    resources :contacts
    resources :enquiries
    resources :users
    resources :helps
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :author_id, :container_id, :container_type, :content_type, :created_on, :description, :digest, :disk_filename, :downloads, :filename, :filesize
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id, :position
  has_many :products, :order=>"position"

  belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id
  has_many :children, :class_name => "Category", :foreign_key => :parent_id, :order=>"position"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  attr_accessible :products, :status, :user_email, :user_id, :user_name
end

app/models/help.rb
class Help < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :colour, :content, :hot, :name, :order_code, :position, :type
  set_inheritance_column nil
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :abn, :email, :hashed_password, :name, :phone, :salt, :skype
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "front"

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout "front"

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  layout "front"

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(params[:enquiry])

    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render json: @enquiry, status: :created, location: @enquiry }
      else
        format.html { render action: "new" }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout "front"

  def home

  end

  def company

  end

  def faq

  end

  def contact

  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  layout "front"

  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "front"

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin,@product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br />
    <%= collection_select(:product, :category_id, @categories, :id, :name, {:prompt => true })  %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hot %><br />
    <%= f.check_box :hot %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :colour %><br />
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :order_code %><br />
    <%= f.text_field :order_code %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Name</th>
    <th>Hot</th>
    <th>Position</th>
    <th>Colour</th>
    <th>Order code</th>
    <th>Type</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.category.try :name %></td>
    <td><%= product.name %></td>
    <td><%= product.hot %></td>
    <td><%= product.position %></td>
    <td><%= product.colour %></td>
    <td><%= product.order_code %></td>
    <td><%= product.type %></td>
    <td><%= product.content %></td>
    <td><%= link_to 'Show', admin_product_path(product) %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
    <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @product.category.try :name %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Hot:</b>
  <%= @product.hot %>
</p>

<p>
  <b>Position:</b>
  <%= @product.position %>
</p>

<p>
  <b>Colour:</b>
  <%= @product.colour %>
</p>

<p>
  <b>Order code:</b>
  <%= @product.order_code %>
</p>

<p>
  <b>Type:</b>
  <%= @product.type %>
</p>

<p>
  <b>Content:</b>
  <%= @product.content %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Name</th>
    <th>Hot</th>
    <th>Position</th>
    <th>Colour</th>
    <th>Order code</th>
    <th>Type</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.category.try :name %></td>
    <td><%= product.name %></td>
    <td><%= product.hot %></td>
    <td><%= product.position %></td>
    <td><%= product.colour %></td>
    <td><%= product.order_code %></td>
    <td><%= product.type %></td>
    <td><%= product.content %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @product.category.try :name %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Hot:</b>
  <%= @product.hot %>
</p>

<p>
  <b>Position:</b>
  <%= @product.position %>
</p>

<p>
  <b>Colour:</b>
  <%= @product.colour %>
</p>

<p>
  <b>Order code:</b>
  <%= @product.order_code %>
</p>

<p>
  <b>Type:</b>
  <%= @product.type %>
</p>

<p>
  <b>Content:</b>
  <%= @product.content %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>