config/routes.rb
Led::Application.routes.draw do
  root :to => "front#home"
  match 'front(/:action)', :controller => 'front'

  resources :products
  resources :categories
  resources :news
  resources :contacts
  resources :enquiries
  resources :users
  resources :helps

  namespace :admin do
    root :to=>"products#index"

    resources :products
    resources :categories
    resources :news
    resources :contacts
    resources :enquiries
    resources :users
    resources :helps
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :author_id, :container_id, :container_type, :content_type, :created_on, :description, :digest, :disk_filename, :downloads, :filename, :filesize
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id, :position
  has_many :products, :order=>"position"

  belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id
  has_many :children, :class_name => "Category", :foreign_key => :parent_id, :order=>"position"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  attr_accessible :products, :status, :user_email, :user_id, :user_name
end

app/models/help.rb
class Help < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :colour, :content, :hot, :name, :order_code, :position, :type
  set_inheritance_column nil
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :abn, :email, :hashed_password, :name, :phone, :salt, :skype
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout "front"

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  layout "front"

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(params[:enquiry])

    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render json: @enquiry, status: :created, location: @enquiry }
      else
        format.html { render action: "new" }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout "front"

  def home

  end

  def company

  end

  def faq

  end

  def contact

  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  layout "front"

  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "front"

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin,@user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :abn %><br />
    <%= f.text_field :abn %>
  </div>
  <div class="field">
    <%= f.label :skype %><br />
    <%= f.text_field :skype %>
  </div>
  <div class="field">
    <%= f.label :hashed_password %><br />
    <%= f.text_field :hashed_password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Abn</th>
    <th>Skype</th>
    <th>Hashed password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= user.abn %></td>
    <td><%= user.skype %></td>
    <td><%= user.hashed_password %></td>
    <td><%= user.salt %></td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>

<p>
  <b>Abn:</b>
  <%= @user.abn %>
</p>

<p>
  <b>Skype:</b>
  <%= @user.skype %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>