config/routes.rb
Led::Application.routes.draw do
  root :to => "front#home"
  match 'front(/:action)', :controller => 'front'

  resources :products
  resources :categories
  resources :news
  resources :contacts
  resources :enquiries
  resources :users
  resources :helps

  namespace :admin do
    root :to=>"products#index"

    resources :products
    resources :categories
    resources :news
    resources :contacts
    resources :enquiries
    resources :users
    resources :helps
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :author_id, :container_id, :container_type, :content_type, :created_on, :description, :digest, :disk_filename, :downloads, :filename, :filesize
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id, :position
  has_many :products, :order=>"position"

  belongs_to :parent, :class_name => "Category", :foreign_key => :parent_id
  has_many :children, :class_name => "Category", :foreign_key => :parent_id, :order=>"position"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  attr_accessible :products, :status, :user_email, :user_id, :user_name
end

app/models/help.rb
class Help < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :colour, :content, :hot, :name, :order_code, :position, :type
  set_inheritance_column nil
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :abn, :email, :hashed_password, :name, :phone, :salt, :skype
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout "front"

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout "front"

  def home

  end

  def company

  end

  def faq

  end

  def contact

  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  layout "front"

  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Led</title>
  <%= stylesheet_link_tag    "admin", :media => "all" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav">
  <li><%= link_to_unless_current :categories, admin_categories_path %></li>
  <li><%= link_to_unless_current :products, admin_products_path %></li>
  <li><%= link_to_unless_current :users, admin_users_path %></li>
  <li><%= link_to_unless_current :news, admin_news_index_path %></li>
  <li><%= link_to_unless_current :enquiries, admin_enquiries_path %></li>
  <li><%= link_to_unless_current :contacts, admin_contacts_path %></li>
  <li><%= link_to_unless_current "公司简介", admin_help_path(:about_company) %></li>
  <li><%= link_to_unless_current "FQA", admin_help_path(:about_faq) %></li>
  <li><%= link_to_unless_current "联系方式", admin_help_path(:about_contact) %></li>
</ul>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Led</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav">
  <li><%= link_to_unless_current :categories, categories_path %> | </li>
  <li><%= link_to_unless_current :products, products_path %> | </li>
  <li><%= link_to_unless_current :users, users_path %> | </li>
  <li><%= link_to_unless_current :news, news_index_path %> | </li>
  <li><%= link_to_unless_current :enquiries, enquiries_path %> | </li>
  <li><%= link_to_unless_current :contacts, contacts_path %> | </li>
</ul>

<%= yield %>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Led</title>
  <%= stylesheet_link_tag    "front", :media => "all" %>
  <%= javascript_include_tag "front" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav">
  <li><%= link_to_unless_current :categories, categories_path %></li>
  <li><%= link_to_unless_current :products, products_path %></li>
  <li><%= link_to_unless_current :users, users_path %></li>
  <li><%= link_to_unless_current :news, news_index_path %></li>
  <li><%= link_to_unless_current :enquiries, enquiries_path %></li>
  <li><%= link_to_unless_current :contacts, contacts_path %></li>
  <li><%= link_to_unless_current "公司简介", help_path(:about_company) %></li>
  <li><%= link_to_unless_current "FQA", help_path(:about_faq) %></li>
  <li><%= link_to_unless_current "联系方式", help_path(:about_contact) %></li>
</ul>

<%= yield %>

</body>
</html>